#ifndef OTWP_H
#define OTWP_H

#ifdef __cplusplus
extern "C" {
#endif
#define TYRIAN_MENU_MAIN					0
#define TYRIAN_MENU_NEW_GAME				1
#define TYRIAN_MENU_LOAD_GAME				2
#define TYRIAN_MENU_HIGH_SCORES				3
#define TYRIAN_MENU_INSTRUCTIONS			4
#define TYRIAN_MENU_OPENTYRIAN				5

#define TYRIAN_MENU_SELECT_NEW_GAME			10
#define TYRIAN_MENU_SELECT_LOAD_GAME		20
#define TYRIAN_MENU_SELECT_HIGH_SCORES		30
#define TYRIAN_MENU_SELECT_INSTRUCTIONS		40
#define TYRIAN_MENU_SELECT_OPENTYRIAN		50
#define TYRIAN_MENU_SELECT_DEMO				60
#define TYRIAN_MENU_SELECT_QUIT				70

#define TYRIAN_MENU_SELECT_FULL_GAME		11
#define TYRIAN_MENU_SELECT_ARCADE_1_GAME	12
#define TYRIAN_MENU_SELECT_ARCADE_2_GAME	13

#define TYRIAN_MENU_SELECT_EPISODE_1		111
#define TYRIAN_MENU_SELECT_EPISODE_2		112
#define TYRIAN_MENU_SELECT_EPISODE_3		113
#define TYRIAN_MENU_SELECT_EPISODE_4		114

#define TYRIAN_MENU_SELECT_DIFF_EASY		115
#define TYRIAN_MENU_SELECT_DIFF_NORMAL		116
#define TYRIAN_MENU_SELECT_DIFF_HARD		117

#define TYRIAN_MENU_SELECT_HELP_1P			41
#define TYRIAN_MENU_SELECT_HELP_2P			42
#define TYRIAN_MENU_SELECT_HELP_UPGRADE		43
#define TYRIAN_MENU_SELECT_HELP_OPTIONS		44

#define TYRIAN_MENU_SELECT_OT_ABOUT			0
#define TYRIAN_MENU_SELECT_OT_JUKEBOX		1

#define TYRIAN_MENU_KEYBOARD				254
#define TYRIAN_MENU_SELECT_NONE				255


#define GAME_MENU_MAIN					0
#define GAME_MENU_DATA					1
#define GAME_MENU_UPGRADE				3
#define GAME_MENU_OPTIONS				4
#define GAME_MENU_NEXT_LEVEL			5

#define GAME_MENU_UPGRADE_SHIP			30
#define GAME_MENU_UPGRADE_FRONT_GUN		31
#define GAME_MENU_UPGRADE_REAR_GUN		32
#define GAME_MENU_UPGRADE_SHIELD		33
#define GAME_MENU_UPGRADE_GENERATOR		34
#define GAME_MENU_UPGRADE_LEFT_KICK		35
#define GAME_MENU_UPGRADE_RIGHT_KICK	36

#define GAME_MENU_OPTIONS_LOAD			40
#define GAME_MENU_OPTIONS_SAVE			41
#define GAME_MENU_OPTIONS_MUSIC			42
#define GAME_MENU_OPTIONS_SOUND			43

#define GAME_MENU_UPGRADE_SELECT_1		301
#define GAME_MENU_UPGRADE_SELECT_2		302
#define GAME_MENU_UPGRADE_SELECT_3		303
#define GAME_MENU_UPGRADE_SELECT_4		304
#define GAME_MENU_UPGRADE_SELECT_EXIT	305

	void Debug(char*, char*);
	void DebugInt(int, char*, char*);
	void DebugFloat(float, char*, char*);
	void DebugBool(bool, char*, char*);
	void DebugCoordinates(float, float, char*, char*);
	int getMainTouchMenu(int);
	int getGameTouchMenu(int);

#ifdef __cplusplus
}
#endif

#endif